---
root: true
extends: eslint:recommended
env:
  node: true
  es6: true
  es2017: true
parserOptions:
  ecmaVersion: 2019
  impliedStrict: true
  sourceType: module  
rules:
  array-callback-return: 1
  no-console: 1
  no-param-reassign: 2
  no-template-curly-in-string: 1  
  no-useless-call: 1
  semi: 2
