---
extends: '../.eslintrc.yaml'
plugins:
  - jasmine
env:
  jasmine: true
rules:
  no-console: 0
  jasmine/no-assign-spyon: 1
  jasmine/no-disabled-tests: 2
  jasmine/no-focused-tests: 1
  jasmine/prefer-toHaveBeenCalledWith: 1
  jasmine/valid-expect: 2
